### ISSUE TITLE
module polardbx-rpc is missed

### ISSUE THREAD

**Issue by hhofchina** [ApsaraDB/galaxysql#5] opened 2021-10-20 07:01 UTC
[ERROR] Child module /Users/hhao/workspace/galaxysql/polardbx-rpc of /Users/hhao/workspace/galaxysql/pom.xml does not exist @

**Comment by Oldbread3** [comment] 2021-10-20 07:14
Duplicate of #4 

Cause by limitation of License, code of CN was separated into two repo.
If you are building develop environment,  try this [doc](https://github.com/ApsaraDB/galaxysql/blob/main/CONTRIBUTING.md).
If you are building project from source code, try this [doc](https://github.com/ApsaraDB/galaxysql/blob/main/docs/zh_CN/quickstart-development.md).

**Closed as completed by Oldbread3** 2021-10-20 07:14 UTC
Labels: duplicate, good first issue
